/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package crud_java;
import java.sql.*;
import net.proteanit.sql.DbUtils;
import javax.swing.JOptionPane;

/**
 *
 * @author aldil
 */
public class FormSiswa extends javax.swing.JFrame {
    Connection conn = null;
    ResultSet rs = null;
    PreparedStatement pst = null;
    Statement statSiswa;
    Boolean ada = false;
    
    private void koneksi() {
        try {
            Class.forName("com.mysql.jdbc.Driver");
            String url = "jdbc:mysql://localhost:3307/db_crud_java";
            String user = "root";
            String pass = "";
            conn = DriverManager.getConnection(url, user, pass);
            statSiswa = conn.createStatement(rs.TYPE_SCROLL_SENSITIVE, rs.CONCUR_UPDATABLE);
            rs = statSiswa.executeQuery("SELECT * FROM siswa");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
            System.exit(0);
        }
    }
    
    private void tampil() {
        try {
            String sql = "SELECT * FROM siswa";
            pst = conn.prepareStatement(sql);
            rs = pst.executeQuery();
            tblData.setModel(DbUtils.resultSetToTableModel(rs));
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }
    
    private void reset() {
        tfNama.setText("");
        tfNis.setText("");
        tfRombel.setText("");
    }

    /**
     * Creates new form FormSiswa
     */
    public FormSiswa() {
        initComponents();
        koneksi();
        tampil();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblData = new javax.swing.JTable();
        tfNis = new javax.swing.JTextField();
        tfNama = new javax.swing.JTextField();
        tfRombel = new javax.swing.JTextField();
        lblNis = new javax.swing.JLabel();
        lblNama = new javax.swing.JLabel();
        lblRombel = new javax.swing.JLabel();
        btnTambah = new javax.swing.JButton();
        btnGanti = new javax.swing.JButton();
        btnHapus = new javax.swing.JButton();
        btnReset = new javax.swing.JButton();
        btnKeluar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 20, -1, -1));

        tblData.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "nis", "nama", "rombel"
            }
        ));
        tblData.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblDataMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblData);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, -1, -1));
        getContentPane().add(tfNis, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 50, 170, -1));
        getContentPane().add(tfNama, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 90, 170, 20));

        tfRombel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfRombelActionPerformed(evt);
            }
        });
        getContentPane().add(tfRombel, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 130, 170, -1));

        lblNis.setText("NIS");
        getContentPane().add(lblNis, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, -1, -1));

        lblNama.setText("Nama");
        getContentPane().add(lblNama, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, -1, -1));

        lblRombel.setText("Rombel");
        getContentPane().add(lblRombel, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, -1, 20));

        btnTambah.setText("Tambah");
        btnTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTambahActionPerformed(evt);
            }
        });
        getContentPane().add(btnTambah, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 50, -1, -1));

        btnGanti.setText("Ganti");
        btnGanti.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGantiActionPerformed(evt);
            }
        });
        getContentPane().add(btnGanti, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 90, -1, -1));

        btnHapus.setText("Hapus");
        btnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusActionPerformed(evt);
            }
        });
        getContentPane().add(btnHapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 130, -1, -1));

        btnReset.setText("Reset");
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });
        getContentPane().add(btnReset, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 50, -1, -1));

        btnKeluar.setText("Keluar");
        btnKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKeluarActionPerformed(evt);
            }
        });
        getContentPane().add(btnKeluar, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 90, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tfRombelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfRombelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfRombelActionPerformed

    private void btnTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahActionPerformed
        // TODO add your handling code here:
        try {
            koneksi();
            statSiswa = conn.createStatement();
            String SQL = "INSERT INTO siswa VALUES('"+tfNis.getText()+"','"+tfNama.getText()+"','"+tfRombel.getText()+"')";
            statSiswa.executeUpdate(SQL);
            tampil();
            statSiswa.close();
            conn.close();
            reset();
            JOptionPane.showMessageDialog(null, "Data berhasil disimpan!");
        } catch (Exception exc) {
            System.err.println(exc.getMessage());
        }
    }//GEN-LAST:event_btnTambahActionPerformed

    private void btnGantiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGantiActionPerformed
        // TODO add your handling code here:
        try {
            koneksi();
            statSiswa = conn.createStatement();
            String SQL = "UPDATE siswa SET nis = '"+tfNis.getText()+"', nama = '"+tfNama+"', rombel = '"+tfRombel+"'";
            statSiswa.executeUpdate(SQL);
            tampil();
            statSiswa.close();
            conn.close();
            reset();
            JOptionPane.showMessageDialog(null, "Data berhasil dirubah!");
        } catch (Exception exc) {
            System.err.println(exc.getMessage());
        }
    }//GEN-LAST:event_btnGantiActionPerformed

    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed
        // TODO add your handling code here:
        try {
            koneksi();
            statSiswa = conn.createStatement();
            String SQL = "DELETE FROM siswa WHERE nis = '"+tfNis.getText()+"'";
            statSiswa.execute(SQL);
            tampil();
            statSiswa.close();
            conn.close();
            JOptionPane.showMessageDialog(null, "Data berhasil dihapus!");
        } catch (Exception exc) {
            System.err.println(exc.getMessage());
        }
    }//GEN-LAST:event_btnHapusActionPerformed

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        // TODO add your handling code here:
        reset();
    }//GEN-LAST:event_btnResetActionPerformed

    private void btnKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKeluarActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_btnKeluarActionPerformed

    private void tblDataMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblDataMouseClicked
        try {
            koneksi();
            int row = tblData.getSelectedRow();
            String klik_tabel = (tblData.getModel().getValueAt(row, 0).toString());
            java.sql.Statement stm = conn.createStatement();
            java.sql.ResultSet sql = stm.executeQuery("SELECT * FROM siswa WHERE nis = '"+klik_tabel+"");
            if (sql.next()) {
                String nis = sql.getString("nis");
                tfNis.setText(nis);
                String nama = sql.getString("nama");
                tfNis.setText(nama);
                String rombel = sql.getString("rombel");
                tfNis.setText(rombel);
            }
        } catch (Exception e) {
        }        // TODO add your handling code here:
    }//GEN-LAST:event_tblDataMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormSiswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormSiswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormSiswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormSiswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormSiswa().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGanti;
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnKeluar;
    private javax.swing.JButton btnReset;
    private javax.swing.JButton btnTambah;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblNama;
    private javax.swing.JLabel lblNis;
    private javax.swing.JLabel lblRombel;
    private javax.swing.JTable tblData;
    private javax.swing.JTextField tfNama;
    private javax.swing.JTextField tfNis;
    private javax.swing.JTextField tfRombel;
    // End of variables declaration//GEN-END:variables
}
